### ISSUE TITLE
The size of tensor a (12) must match the size of tensor b (8) at non-singleton dimension 1

### ISSUE THREAD

**Issue by tnickMoxuan** [lllyasviel/IC-Light#24]
when i run gradio_demo.py, it report error "The size of tensor a (12) must match the size of tensor b (8) at non-singleton dimension 1" ,which means model "iclight_sd15_fc.safetensors" shape not equal to base model (realistic-vision-v51)

**Comment by ljaccc** [comment]
what, same issue, how to resolve the issue
