### ISSUE TITLE
how to use in a1111 webui? 

### ISSUE THREAD

**Issue by greasebig** [lllyasviel/IC-Light#34]

**Comment by huchenlei** [comment]
Currently ComfyUI and Forge versions are available:
- https://github.com/huchenlei/ComfyUI-IC-Light-Native
- https://github.com/huchenlei/sd-forge-ic-light

I will work on A1111 extension soon.

**Comment by Fridemn** [comment]
give it a go

https://github.com/QodiCat/IC-Light-sd-webui
