### ISSUE TITLE
Why change the unet.conv_in?

### ISSUE THREAD

**Issue by D222097** [lllyasviel/IC-Light#45]
the channel of unet.conv_in is 8/12 in gradio_demo.py/gradio_demo_bg.py, curious how it works in t2i_pipe/i2i_pipe, and how does it get 8/12 channel? Especially if foreground information pass  to unet via cross_attention_kwargs.

**Comment by NeverGiveU** [comment]
> the channel of unet.conv_in is 8/12 in gradio_demo.py/gradio_demo_bg.py, curious how it works in t2i_pipe/i2i_pipe, and how does it get 8/12 channel? Especially if foreground information pass to unet via cross_attention_kwargs.

hi, the unet.forward is modified by "hooked_unet_forward" in gradio_demo*.py, in which firstly the fg (and bg) latent(s) is(are) concatenated to noised sample before the original forward is applied. I think it is quite a smart implementation.

**Comment by NeverGiveU** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好！您的来信我已收到，我将认真阅读邮件并及时予以您答复！谢谢！
