### ISSUE TITLE
不知原因的错误

### ISSUE THREAD

**Issue by zffffff** [lllyasviel/IC-Light#46]
![image](https://github.com/lllyasviel/IC-Light/assets/21136110/66fd1750-14db-493d-8d82-9b5e2a97e100)
![image](https://github.com/lllyasviel/IC-Light/assets/21136110/0908bd5c-dcb0-42b4-8c96-b4c274fdec98)
因为我只是个美术类的用户，也不懂代码什么的……

**Comment by zffffff** [comment]
另外，gradio 升级到 4.29 反而启动不了

**Comment by wchpeng** [comment]
这只是警告，不用管它，继续用就行了。

> 另外，gradio 升级到 4.29 反而启动不了

把gradio再降回3.41.2就可

**Comment by xugaoxiang** [comment]
> ![image](https://private-user-images.githubusercontent.com/21136110/330768751-66fd1750-14db-493d-8d82-9b5e2a97e100.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyOTEyMjAsIm5iZiI6MTcxNzI5MDkyMCwicGF0aCI6Ii8yMTEzNjExMC8zMzA3Njg3NTEtNjZmZDE3NTAtMTRkYi00OTNkLThkODItOWI1ZTJhOTdlMTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDAxMTUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzNDhhNjY0ZWRmZmJmYjFjYzE3ZjdlNjM3MWQ3NGE2OGE4ZDE2YzViMmRkYzk4MDk1ZThjOWM5MjUzNmI2NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.21AafOMkDHTO8keBujvLS9eCHMgFC6lXOte1MC4rRog) ![image](https://private-user-images.githubusercontent.com/21136110/330768776-0908bd5c-dcb0-42b4-8c96-b4c274fdec98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyOTEyMjAsIm5iZiI6MTcxNzI5MDkyMCwicGF0aCI6Ii8yMTEzNjExMC8zMzA3Njg3NzYtMDkwOGJkNWMtZGNiMC00MmI0LThjOTYtYjRjMjc0ZmRlYzk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDAxMTUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZmViNzZhZTYzYTNjNmU0MTc4YjY5ZmQ5NjJhODVlNjBlN2U4MjVkNmY4MmE3YzVhYjE3MTQ1ZDNiOTI1YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lzOaHFnltfYOa5N4mKdPAOt2mYkYpZlLeWXyjVyt-2Q) 因为我只是个美术类的用户，也不懂代码什么的……

+1

**Comment by zffffff** [comment]
又出现了这个问题，上次解决了，又给忘了，好像是网络的问题，好像是要关掉梯子再启动还是什么，等我想起来一定要过来记录一下

**Comment by zffffff** [comment]
解决 —— 启动之前要关掉梯子！

参考（不一定必要）：
1.如果长时间没用了，可以开着梯子先启动一遍，有时候貌似有更新的举动（不确定）；
2.正式使用之前先关掉梯子，启动以后再打开梯子就行，不影响使用；
3.http://127.0.0.1:7860/ 我是用这个地址，不知道有没有关系

**Comment by xugaoxiang** [comment]
> 解决 —— 启动之前要关掉梯子！
> 
> 参考（不一定必要）： 1.如果长时间没用了，可以开着梯子先启动一遍，有时候貌似有更新的举动（不确定）； 2.正式使用之前先关掉梯子，启动以后再打开梯子就行，不影响使用； 3.http://127.0.0.1:7860/ 我是用这个地址，不知道有没有关系

谢谢你的回复。我测试了下，启动之前关闭梯子，然后使用 127.0.0.1:7860 就没有问题了，处理过程中也不需要开梯子。
